= mysql-backup(1) =

== NAME ==

mysql-backup - Backup MySQL databases.

== SYNOPSIS ==

  mysql-backup [ options ] command [ command options ]

== DESCRIPTION ==

+mysql-backup+ performs daily, weekly and monthly backup of MySQL databases.
Features:

  - Backup multiple databases
  - Compress backup files
  - Backup remote servers
  - Rotate backups
  - Perform restoration
  - more...

== ARGUMENTS ==

=== Options ===

-c CONFIG , --config CONFIG::

  A configuration file to use instead of default one. This option allows
  different configuration for different MySQL servers.

-v, verbose::

  Run in verbose mode.

-h, --help::

  Show a short help screen.

=== Commands ===

There are only two commands:

backup::

  Perform the backup.

restore::

  Performs the restoration of a previously done backup.

=== Command options ===

Each command has its own set of options.

==== backup options ====

--dry-run::

  Run backup in a dry-run mode: nothing would be done for real. Commands to
  run are displayed on the screen.

==== Restore options ====

--dry-run::

  Run restore in a dry-run mode: nothing would be done for real. Commands to
  run are displayed on the screen.

--date DATE::

  Restore backups for given date. If this option is not set, the last found
  backup would be restored.

--bases BASES::

  Restore backups for given set of databases. If this option is not set all
  found databases would be restored.

== CONFIGURATION FILE ==

=== Default configuration ===

+mysql-backup+ looks for a default configuration file in that order:

  - '/etc/mysql-backup/default.cnf'
  - '~/.mysql-backup.cnf'
  - './.mysql-backup.cnf'

If no default configuration file is found, default hard-coded values would
be used.

=== Specific configuration file ===

In addition of the default configuration, a specific configuration file can
be used (with the *--conf* option).

==== General options ====

BACKUP_DIR::

  Where the backups files would be stored. A generic backup file schema is:

    <BACKUP_DIR>/<host>/<daily|weekly|monthly>/<base>_YYYY-MM-DD.sql[.<COMPRESSION_EXTENSION>]

==== MySQL options ====

DATABASES::

  Databases to backup. If this value is set to *ALL* then all databases
  would be backuped.  +mysql-backup+ would determine the database using the
  "SHOW DATABASES" query.

IGNORE_DATABASES::

  A list of database to ignore during backup. By default,
  *information_schema* is ignored.

In addition to that option all mysql(1) and mysqldump(1) options are also
recognized as long as dash (*-*) are changed to underscore (*_*).

NOTE: However some options are not recognized: *help*, *pipe*, *table*,
*version*, *databases*, *ignore-table*, *ssl**, *execute*.

EXAMPLE: This is the default MySQL configuration:

  batch=1
  skip_column_names=1
  quote_names=1
  opt=1
  add_drop_database=1


==== Archive options ====

COMPRESSION::

  The tool to use for compression. Currently *gzip*, *bzip2* and *xz* are
  recognized. If compression if not known then no compression would be used.

NOTE: *gzip* generates bigger files than the others but needs less CPU time.

COMPRESSION_OPTS::

  Options to pass to the compression tool.

DAILY_RETENTION::

  How many days a daily backup should be kept. By default daily archives are
  kept 7 days.

WEEKLY_RETENTION::

  How many days a weekly backup should be kept. By default weekly archives are
  kept 35 days (5 weeks).

MONTHLY_RETENTION::

  How many days a monthly backup should be kept. By default monthly archives
  are kept 365 days (12 months).

WEEKLY_DAY::

  Which day weekly backup are done (0..6, 0 is Sunday).

MONTHLY_DAY::

  Which day monthly backup are done (00..31).

HOST::

  Name of the host to backup for logging purposes.


NOTE: This is not the mysql host to backup (use "host" in lowercase for
that).

==== Hooks ====

Hooks are scripts that can be run via *run-parts*(1).

pre_backup_hook::

  Hook to be run before the backup process really starts.

post_backup_hook::

  Hook to be run after the backup process is done.

pre_restore_hook::

  Hook to be run before the restore process really starts.

post_restore_hook::

  Hook to be run after the restore process is done.

NOTE: In addition hook names could be postfixed with a database name. This
means a hook could be defined for a specific database.

EXAMPLE: *post_backup_hook_a_database* is ran before *a_database* would be
backuped.

See *run-parts*(8) for further information on how hooks are run.

== ARCHIVE PROCEDURE ==

Every day backups are done in the *daily* directory. On *WEEKLY_DAY* the
daily backup is hard linked to the *weekly* directory (the same is done for
monthly backups on *MONTHLY_DAY* and *monthly* directory).

After that archives older that *DAILY_RETENTION*, *WEEKLY_RETENTION* and
*MONTHLY_RETENTION* are removed from their specific directories.

This system keeps space on the backup server by the use of hard links.

NOTE: This only woks if all backups are in a single partition.



== SEE ALSO ==

 - mysql(1)
 - mysqldump(1)
 - gzip(1), bzip2(1), xz(1)
 - run-parts(8)

== HISTORY ==

=== Version 1.0 ===

2010-09-06::

  First release.

== BUGS ==

No time to include bugs, command actions might seldom lead astray
user's assumption.

== AUTHORS ==

+mysql-backup+ is written by Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>.

== COPYRIGHT ==

Copyright © 2010 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>.

Released under GNU GPL version 3 or higher
(http://www.gnu.org/licenses/gpl.html[]).
